module Flavor (getAncestryFlavor, getBackgroundFlavor, getClassFlavor) where

import Types

getAncestryFlavor :: Ancestry -> String
getAncestryFlavor Dwarf =
  "If you want to play a character who is as hard as nails, "
    ++ "a stubborn and unrelenting adventurer, with a mix of "
    ++ "rugged toughness and deep wisdom—or at least dogged "
    ++ "conviction—you should play a dwarf."
getAncestryFlavor Elf =
  "If you want a character who is "
    ++ "magical, mystical, and mysterious, "
    ++ "you should play an elf."
getAncestryFlavor Gnome =
  "If you want a character with boundless enthusiasm "
    ++ "and an alien, fey outlook on morality and life, you should "
    ++ "play a gnome."
getAncestryFlavor Goblin =
  "If you want a character who is eccentric, enthusiastic, "
    ++ "and fun-loving, you should play a goblin."
getAncestryFlavor Halfling =
  "If you want to play a character who must contend with "
    ++ "these opposing drives toward adventure and comfort, "
    ++ "you should play a halfling."
getAncestryFlavor Human =
  "If you want a character who can be "
    ++ "just about anything, you should play a human."
getAncestryFlavor _ = "Coming soon.."

getBackgroundFlavor :: Background -> String
getBackgroundFlavor Acolyte =
  "You spent your early days in a religious monastery or "
    ++ "cloister. You may have traveled out into the world to spread "
    ++ "the message of your religion or because you cast away the "
    ++ "teachings of your faith, but deep down you’ll always carry "
    ++ "within you the lessons you learned."
getBackgroundFlavor Acrobat =
  "In a circus or on the streets, you earned your pay by "
    ++ "performing as an acrobat. You might have turned to "
    ++ "adventuring when the money dried up, or simply decided to "
    ++ "put your skills to better use."
getBackgroundFlavor AnimalWhisperer =
  "You have always felt a connection to animals, and it was "
    ++ "only a small leap to learn to train them. As you travel, you "
    ++ "continuously encounter different creatures, befriending them "
    ++ "along the way."
getBackgroundFlavor Artisan =
  "As an apprentice, you practiced a particular form of building "
    ++ "or crafting, developing specialized skill. You might have been "
    ++ "a blacksmith’s apprentice toiling over the forge for countless "
    ++ "hours, a young tailor sewing garments of all kinds, or a "
    ++ "shipwright shaping the hulls of ships."
getBackgroundFlavor Artist =
  "Your art is your greatest passion, whatever form it takes. "
    ++ "Adventuring might help you find inspiration, or simply be a "
    ++ "way to survive until you become a world-famous artist."
getBackgroundFlavor Barkeep =
  "You have five specialties: hefting barrels, drinking, polishing "
    ++ "steins, drinking, and drinking. You worked in a bar, where you "
    ++ "learned how to hold your liquor and rowdily socialize."
getBackgroundFlavor Barrister =
  "Piles of legal manuals, stern teachers, and experience in the "
    ++ "courtroom have instructed you in legal matters. You’re capable "
    ++ "of mounting a prosecution or defense in court, and you tend "
    ++ "to keep abreast of local laws, as you never can tell when you "
    ++ "might need to know them on short notice."
getBackgroundFlavor BountyHunter =
  "Bringing in lawbreakers lined your pockets. Maybe you had an "
    ++ "altruistic motive and sought to bring in criminals to make the "
    ++ "streets safer, or maybe the coin was motivation enough. Your "
    ++ "techniques for hunting down criminals transfer easily to the "
    ++ "life of an adventurer."
getBackgroundFlavor Charlatan =
  "You traveled from place to place, peddling false fortunes and "
    ++ "snake oil in one town, pretending to be royalty in exile to seduce "
    ++ "a wealthy heir in the next. Becoming an adventurer might be "
    ++ "your next big scam or an attempt to put your talents to use for a "
    ++ "greater cause. Perhaps it’s a bit of both, as you realize that after "
    ++ "pretending to be a hero, you’ve become the mask."
getBackgroundFlavor Criminal =
  "As an unscrupulous independent or as a member of an "
    ++ "underworld organization, you lived a life of crime. You might "
    ++ "have become an adventurer to seek redemption, to escape the "
    ++ "law, or simply to get access to bigger and better loot."
getBackgroundFlavor Detective =
  "You solved crimes as a police inspector or took jobs for "
    ++ "wealthy clients as a private investigator. You might have "
    ++ "become an adventurer as part of your next big mystery, "
    ++ "but likely it was due to the consequences or aftermath of "
    ++ "a prior case."
getBackgroundFlavor Emissary =
  "As a diplomat or messenger, you traveled to lands far and "
    ++ "wide. Communicating with new people and forming alliances "
    ++ "were your stock and trade."
getBackgroundFlavor Entertainer =
  "Through an education in the arts or sheer dogged practice, "
    ++ "you learned to entertain crowds. You might have been an "
    ++ "actor, a dancer, a musician, a street magician, or any other "
    ++ "sort of performer."
getBackgroundFlavor Farmhand =
  "With a strong back and an understanding of seasonal cycles, "
    ++ "you tilled the land and tended crops. Your farm could have "
    ++ "been razed by invaders, you could have lost the family tying "
    ++ "you to the land, or you might have simply tired of the drudgery, "
    ++ "but at some point you became an adventurer."
getBackgroundFlavor FieldMedic =
  "In the chaotic rush of battle, you learned to adapt to rapidly "
    ++ "changing conditions as you administered to battle casualties. "
    ++ "You patched up soldiers, guards, or other combatants, and "
    ++ "learned a fair amount about the logistics of war."
getBackgroundFlavor FortuneTeller =
  "The strands of fate are clear to you, as you have learned many "
    ++ "traditional forms by which laypeople can divine the future. "
    ++ "You might have used these skills to guide your community, or "
    ++ "simply to make money. But even the slightest peek into these "
    ++ "practices connects you to the occult mysteries of the universe."
getBackgroundFlavor Gambler =
  "The thrill of the win drew you into games of chance. This "
    ++ "might have been a lucrative sideline that paled in comparison "
    ++ "to the real risks of adventuring, or you might have fallen on "
    ++ "hard times due to your gambling and pursued adventuring as "
    ++ "a way out of a spiral."
getBackgroundFlavor Gladiator =
  "The bloody games of the arena taught you the art of combat. "
    ++ "Before you attained true fame, you departed—or escaped—the "
    ++ "arena to explore the world. Your skill at drawing both blood "
    ++ "and a crowd’s attention pay off in a new adventuring life."
getBackgroundFlavor Guard =
  "You served in the guard, out of either patriotism or the need for "
    ++ "coin. Either way, you know how to get a difficult suspect to talk. "
    ++ "However you left the guard, you might think of adventuring as "
    ++ "a way to use your skills on a wider stage."
getBackgroundFlavor Herbalist =
  "As a formally trained apothecary or a rural practitioner of folk "
    ++ "medicine, you learned the healing properties of various herbs. "
    ++ "You’re adept at collecting the right natural cures in all sorts of "
    ++ "environments and preparing them properly."
getBackgroundFlavor Hermit =
  "In an isolated place—like a cave, remote oasis, or secluded "
    ++ "mansion—you lived a life of solitude. Adventuring might "
    ++ "represent your first foray out among other people in some time. "
    ++ "This might be a welcome reprieve from solitude or an unwanted "
    ++ "change, but in either case, you’re likely still rough around "
    ++ "the edges."
getBackgroundFlavor Hunter =
  "You stalked and took down animals and other creatures of "
    ++ "the wild. Skinning animals, harvesting their flesh, and cooking "
    ++ "them were also part of your training, all of which can give you "
    ++ "useful resources while you adventure."
getBackgroundFlavor Laborer =
  "You’ve spent years performing arduous physical labor. It was "
    ++ "a difficult life, but you somehow survived. You may have "
    ++ "embraced adventuring as an easier method to make your "
    ++ "way in the world, or you might adventure under someone "
    ++ "else’s command."
getBackgroundFlavor MartialDisciple =
  "You dedicated yourself to intense training and rigorous "
    ++ "study to become a great warrior. The school you attended "
    ++ "might have been a traditionalist monastery, an elite "
    ++ "military academy, or the local branch of a prestigious "
    ++ "mercenary organization."
getBackgroundFlavor Merchant =
  "In a dusty shop, market stall, or merchant caravan, you "
    ++ "bartered wares for coin and trade goods. The skills you picked "
    ++ "up still apply in the adventuring life, in which a good deal on a "
    ++ "suit of armor could prevent your death."
getBackgroundFlavor Miner =
  "You earned a living wrenching precious minerals from the "
    ++ "lightless depths of the earth. Adventuring might have seemed "
    ++ "lucrative or glamorous compared to this backbreaking labor— "
    ++ "and if you have to head back underground, this time you plan "
    ++ "to do so armed with a real weapon instead of a miner’s pick."
getBackgroundFlavor Noble =
  "To the common folk, the life of a noble seems "
    ++ "one of idyllic luxury, but growing up "
    ++ "as a noble or member of the aspiring "
    ++ "gentry, you know the reality: a noble’s "
    ++ "lot is obligation and intrigue. Whether "
    ++ "you seek to escape your duties by "
    ++ "adventuring or to better your station, "
    ++ "you have traded silks and pageantry for "
    ++ "an adventurer’s life."
getBackgroundFlavor Nomad =
  "Traveling far and wide, you picked up basic tactics for "
    ++ "surviving on the road and in unknown lands, getting by with "
    ++ "few supplies and even fewer comforts. As an adventurer, you "
    ++ "travel still, often into even more dangerous places."
getBackgroundFlavor Prisoner =
  "You might have been imprisoned for crimes (whether you were "
    ++ "guilty or not), or enslaved for some part of your upbringing. "
    ++ "In your adventuring life, you take full advantage of your "
    ++ "newfound freedom."
getBackgroundFlavor Sailor =
  "You heard the call of the sea from a young age. Perhaps you "
    ++ "signed onto a merchant’s vessel, joined the navy, or even fell "
    ++ "in with a crew of pirates and scalawags."
getBackgroundFlavor Scholar =
  "You have a knack for learning, and sequestered yourself "
    ++ "from the outside world to learn all you could. "
    ++ "You read about so many wondrous places and things in your books, "
    ++ "and always dreamed about one day seeing the real things. "
    ++ "Eventually, that curiosity led you to leave your studies and "
    ++ "become an adventurer."
getBackgroundFlavor Scout =
  "You called the wilderness home as you found trails and guided "
    ++ "travelers. Your wanderlust could have called you to the "
    ++ "adventuring life, or perhaps you served as a scout for soldiers "
    ++ "and found you liked battle."
getBackgroundFlavor StreetUrchin =
  "You eked out a living by picking pockets on the streets of "
    ++ "a major city, never knowing where you’d find your next "
    ++ "meal. While some folk adventure for the glory, you do so "
    ++ "to survive."
getBackgroundFlavor Tinker =
  "Creating all sorts of minor inventions scratches your itch for "
    ++ "problem-solving. Your engineering skills take a particularly "
    ++ "creative bent, and no one know what you’ll come up with next. "
    ++ "It might be a genius device with tremendous potential... or it "
    ++ "might explode."
getBackgroundFlavor Warrior =
  "In your younger days, you waded into battle as a mercenary, "
    ++ "a warrior defending a nomadic people, or a member of a "
    ++ "militia or army. You might have wanted to break out from "
    ++ "the regimented structure of these forces, or you could have "
    ++ "always been as independent a warrior as you are now."

getClassFlavor :: Class -> String
getClassFlavor Alchemist =
  "There’s no sight more beautiful to you than a strange brew bubbling in a beaker, "
    ++ "and you consume your ingenious elixirs with abandon. You’re fascinated by "
    ++ "uncovering the secrets of science and the natural world, and you’re constantly "
    ++ "experimenting in your lab or on the go with inventive concoctions for every eventuality. "
    ++ "You are fearless in the face of risk, hurling explosive or toxic creations at your foes. "
    ++ "Your unique path toward greatness is lined with alchemical brews that push your "
    ++ "mind and body to their limits."
getClassFlavor Barbarian =
  "Rage consumes you in battle. You delight in wreaking havoc and using powerful "
    ++ "weapons to carve through your enemies, relying on astonishing durability without "
    ++ "needing complicated techniques or rigid training. Your rages draw upon a vicious "
    ++ "instinct, which you might associate with an animal, a spirit, or some part of yourself. "
    ++ "To many barbarians, brute force is a hammer and every problem looks like a nail, "
    ++ "whereas others try to hold back the storm of emotions inside them and release "
    ++ "their rage only when it matters most."
getClassFlavor Bard =
  "You are a master of artistry, a scholar of hidden secrets, and a captivating "
    ++ "persuader. Using powerful performances, you influence minds and elevate "
    ++ "souls to new levels of heroics. You might use your powers to become a "
    ++ "charismatic leader, or perhaps you might instead be a counselor, manipulator, "
    ++ "scholar, scoundrel, or virtuoso. While your versatility leads some to consider "
    ++ "you a beguiling ne’er-do-well and a jack-of-all-trades, it’s dangerous to "
    ++ "dismiss you as a master of none."
getClassFlavor Champion =
  "You are an emissary of a deity, a devoted servant who has taken up a weighty "
    ++ "mantle, and you adhere to a code that holds you apart from those around "
    ++ "you. While champions exist for every alignment, as a champion of good, you "
    ++ "provide certainty and hope to the innocent. You have powerful defenses that "
    ++ "you share freely with your allies and innocent bystanders, as well as holy "
    ++ "power you use to end the threat of evil. Your devotion even attracts the "
    ++ "attention of holy spirits who aid you on your journey."
getClassFlavor Cleric =
  "Deities work their will upon the world in infinite ways, and you serve as one "
    ++ "of their most stalwart mortal servants. Blessed with divine magic, you live the "
    ++ "ideals of your faith, adorn yourself with the symbols of your church, and train "
    ++ "diligently to wield your deity’s favored weapon. Your spells might protect and "
    ++ "heal your allies, or they might punish foes and enemies of your faith, as your "
    ++ "deity wills. Yours is a life of devotion, spreading the teachings of your faith "
    ++ "through both word and deed."
getClassFlavor Druid =
  "The power of nature is impossible to resist. It can bring ruin to the stoutest "
    ++ "fortress in minutes, reducing even the mightiest works to rubble, burning them "
    ++ "to ash, burying them beneath an avalanche of snow, or drowning them beneath "
    ++ "the waves. It can provide endless bounty and breathtaking splendor to those "
    ++ "who respect it—and an agonizing death to those who take it too lightly. You "
    ++ "are one of those who hear nature’s call. You stand in awe of the majesty of its "
    ++ "power and give yourself over to its service."
getClassFlavor Fighter =
  "Fighting for honor, greed, loyalty, or simply the thrill of battle, you are an "
    ++ "undisputed master of weaponry and combat techniques. You combine your "
    ++ "actions through clever combinations of opening moves, finishing strikes, and "
    ++ "counterattacks whenever your foes are unwise enough to drop their guard. "
    ++ "Whether you are a knight, mercenary, sharpshooter, or blade master, you have "
    ++ "honed your martial skills into an art form and perform devastating critical "
    ++ "attacks on your enemies."
getClassFlavor Monk =
  "The strength of your fist flows from your mind and spirit. You seek "
    ++ "perfection—honing your body into a flawless instrument and your mind into "
    ++ "an orderly bastion of wisdom. You’re a fierce combatant renowned for martial "
    ++ "arts skills and combat stances that grant you unique fighting moves. While "
    ++ "the challenge of mastering many fighting styles drives you to great heights, "
    ++ "you also enjoy meditating on philosophical questions and discovering new ways "
    ++ "to obtain peace and enlightenment."
getClassFlavor Ranger =
  "Some rangers believe civilization wears down the soul, but still needs to be "
    ++ "protected from wild creatures. Others say nature needs to be protected from "
    ++ "the greedy, who wish to tame its beauty and plunder its treasures. You could "
    ++ "champion either goal, or both. You might be a scout, tracker, or hunter of "
    ++ "fugitives or beasts, haunting the edge of civilization or exploring the wilds. "
    ++ "You know how to live off the land and are skilled at spotting and taking down "
    ++ "both opportune prey and hated enemies."
getClassFlavor Rogue =
  "You are skilled and opportunistic. Using your sharp wits and quick reactions, "
    ++ "you take advantage of your opponents’ missteps and strike where it hurts "
    ++ "most. You play a dangerous game, seeking thrills and testing your skills, and "
    ++ "likely don’t care much for any laws that happen to get in your way. While "
    ++ "the path of every rogue is unique and riddled with danger, the one thing "
    ++ "you all share in common is the breadth and depth of your skills."
getClassFlavor Sorcerer =
  "You didn’t choose to become a spellcaster—you were born one. There’s magic "
    ++ "in your blood, whether a divinity touched one of your ancestors, a forebear "
    ++ "communed with a primal creature, or a powerful occult ritual influenced your "
    ++ "line. Self-reflection and study allow you to refine your inherent magical "
    ++ "skills and unlock new, more powerful abilities. The power in your blood "
    ++ "carries a risk, however, and you constantly face the choice of whether you’ll "
    ++ "rise to become a master spellcaster or fall into destruction."
getClassFlavor Wizard =
  "You are an eternal student of the arcane secrets of the universe, using your "
    ++ "mastery of magic to cast powerful and devastating spells. You treat magic "
    ++ "like a science, cross-referencing the latest texts on practical spellcraft "
    ++ "with ancient esoteric tomes to discover and understand how magic works. "
    ++ "Yet magical theory is vast, and there’s no way you can study it all. You "
    ++ "either specialize in one of the eight schools of magic, gaining deeper "
    ++ "understanding of the nuances of those spells above all others, or favor a "
    ++ "broader approach that emphasizes the way all magic comes together at the "
    ++ "expense of depth."
